const quotes = [
    "Attention, ce flim n'est pas un flim sur le cyclimse, merci de votre compréhension.<br>Entre l'Australia et la South America, dans l'océan South Pacific, l'atoll de Pom Pom Galli.",

    "V12 appelle le capitaine Georges Abitbol! V12 appelle le capitaine Georges Abitbol ! Quelqu'un vous demande sur le pont.<br>Qui ?<br>Un dénommé José.<br>Ok, j'arrive V12.",

    "Ah, voilà enfin le roi de la classe, l'homme trop bien sapé : Abitbol ! Alors comme ça, t'as été élu l'homme le plus classe du monde. Laisse-moi rire, style le grand cowboy des fonds marins, genre qui fait rêver les ménagères. Sauf que moi j'les baise les ménagères. Non ? C'est pas vrai ?<br>Écoute moi bien mon p'tit José. Tu baises les ménagères, bien, tu dois avoir le cul qui brille. Mais c'est pas ça qu'on appelle la classe. J'te dis ça en qualité d'homme le plus classe du monde. <br>Hey, je t'arrête tout de suite. La classe, c'est d'être chic dans sa manière de s'habiller. Rien de tel que d'aller chez Azédin Ahlahïa ou même de s'acheter des sous-pulls, chez Ioji Yamamoto.",

    "Excuse-moi de te dire ça mon pauvre José, mais tu confonds un peu tout. Tu fais un amalgame entre la coquetterie et la classe. Tu es fou, tu dépenses tout ton argent dans les habits et accessoires de modes, mais tu es ridicule. Enfin, si ça te plait, c'est toi qui les porte. Mais moi si tu veux mon opinion, ça fait un peu 'has been'.<br>Oh la vache ! Moi ? j'ai l'air Has been ? J'en ai pour plus d'une barre de fringue sur moi, alors va te faire mettre!<br>Tu n'es vraiment pas très sympa. Mais le train de tes injures roule sur le rail de mon indifférence. Je préfère partir plutôt que d'entendre ça, plutôt que d'être sourd.<br>Bien ! Considère qu'on est plus amis ! Abitbol...",

    "Tiens regarde! les Anglais ont débarqué. On va être obligé de passer par derrière. Tu sais, par ce long tunnel tout sombre qui sent pas très bon.<br>Oh Georges, quel poète vous faites, vous me surprenez. On ne m'a jamais parlé comme ça. J'ai connu des hommes, mais jamais des comme vous.<br>Hey, tu sais à qui tu parles là ?<br>Oui !<br>Abritons nous, ça va pas tarder à péter.<br>Et encore, c'est rien.<br>Ahh bravo. Bon pousse toi, laisse moi passer.",

    "Bon V12, c'est quoi ce bordel alors ?<br>Ben ce bordel, c'est qu'il pleut comme vache qui pisse!<br>Ah bravo, merci du renseignement, heureusement qu'tu es là.<br>Mais patron...<br>Quoi 'Patron' ? Tu veux que je dise à tout le monde que ton vrai nom c'est pas V12, c'est Travers de Porc Sel Poivre ? Bon je vais chercher des serviettes éponges avec des imprimés dessus.<br>Ah celle-là... non... Celle-là... ah celle-là, ça va.",

    "Ça c'est bon, c'est épongé... Ça c'est bon, c'est réparé... Ça, ça roule... Oh putain et ça ! Faut pas laisser ça comme ça les enfants !<br>Ohh ah...<br>Georges !...Georges...Oh mon dieu Georges !<br>...ahhh... oh...<br>Aaaaaah, monde de merde.<br>Oh Georges...",

    "Et puis, je vous rappelle la principale information de cette édition : la disparition subite de Georges Abitbol qui depuis plus de quinze ans portait officiellement le titre de l'homme le plus classe du monde.<br>L'Amérique vient de perdre un de ses plus prestigieux ambassadeurs.<br>Et maintenant, un petit peu de musique avec Alain Souchon.<br>Oh non, pas lui !",

    "Bonjour patron, j'peux entrer ?<br>Ah Dave, tu tombes bien, entre. On prépare un dossier sur Georges Abitbol. Tu vas te mettre sur le coup mais tu seras pas tout seul. Tu seras avec Peter et Steven.<br>Peter et Steven... j'les aime bien. Mais pourquoi j'peux pas travailler seul ?<br>Parce que t'es trop mauvais.<br>Ah, ben là patron, vous m'avez convaincu, c'est une bonne raison. Je vais travailler avec Peter et Steven.<br>Ben alors ?<br>Ben ok, j'y vais.",

    "Ce charlot? J'savais pas qu'il existait encore.<br>Ben va falloir vous y habituez parce qu'il va travailler avec vous sur ce dossier. C'est une idée de notre ami Callaghan, une idée lumineuse.<br>Ah arrêtez vos conneries patron. C'est mon fils, mon fiston, pfff... J'sais pas pourquoi, il s'est attaché à moi. Alors, je l'aide.<br>Peut-être qu'il avait personne d'autre à qui s'attacher, mais de quoi on parle là?<br>Ben j'vais te dire de quoi on parle. Où vous en êtes avec la nécro de Georges Abitbol? Vous bossez un peu ? Humm ?<br>On vient de s'y mettre, mais on a déjà quelques p'tites idées.<br>On va interroger des tas de gens. Tout ceux qui l'ont aimé, qui l'ont haï, bref tout ceux qui l'ont approché et qui l'ont connu. Ça fait déjà du boulot.",

    "Quoi d'autre?<br>Et puis, c'est pas tout !<br>Oui, on a pensé qu'on devrait expliquer ses dernières paroles.<br>'Monde de Merde' Vous avez raison.<br>Ouais, on en a chié pour trouver c'te idée. On était charette.<br>L'homme le plus classe du monde meurt, et ses dernières paroles c'est 'monde de merde'. Pourquoi il a dit ça ? C'est ce que j'veux savoir!<br>Merci, c'est pas facile à trouver. C'est sûrement un nom, si c'est une femme, je veux savoir quelle femme. Si c'est un cheval, je veux savoir dans quelle course!<br>Nous, on pensait que ça pouvait être un traîneau.",

    "Bonjour, c'est moi Orson Welles. Ceci est ma maison que vous voyez derrière là. Pas mal non? C'est Français.<br>Je m'permets d'interrompre ce flim parce qu'on s'fout un peu de ma gueule. C'est du vol et du plagiat.<br>J'aime pas trop les voleurs et les fils de pute. Dans ce flim, le héros meurt au début et des journalistes décident d'enquêter sur ses dernières paroles... Comme dans Citizen Kane.<br>J'appelle ça du plagiat. Les journalistes vont interviewer des gens sur le héros. Vous allez voir que les témoignages, ça va être des flashbacks. J'le vois trop arrivé.<br>Aaaaaah... rosebud !",

    "Bon, et à part ça ?<br>Ben, à part ça, on est un peu coincés, on a pas l'ombre d'une piste.<br>Vous savez qu'il a vécu au Texas la moitié de sa vie. Faut chercher par là.<br>'Faut chercher par là', 'faut chercher par là', vous êtes gonflé vous, 'faut chercher par là'.<br>Bravo, quel enthousiasme.<br>Mais au fait, j'y pense : Callaghan, il devrait pouvoir vous aider depuis le temps qu'il est là payé à rien foutre. Autant qu'il serve à quelque chose, ce gros porc.<br>J'suis peut-être payé à rien foutre, mais mes tuyaux, j'les garde pour mon fils.<br>Ah, eh oh la honte!...<br>Mais comprenez moi mes amis, c'est mon fils, ma bataille, c'est le fruit de mes entrailles quoi. J'avais un nom, une adresse, ben j'lui ai donné.<br>Oh le lourd.<br>On dirait que ça vous emmerde, je m'trompe ?",

    "Connasse.<br>C'est vous qui m'avez traité de connasse ?<br>Mais non.<br>Vous savez, c'est pas très agréable.<br>Bonjour, je viens voir un certain Monsieur Hugues.<br>Hey, c'est quoi ça ?<br>Oh va te faire foutre !<br>Vous dites que j'aille me faire foutre? Ok, j'y vais.<br>Pff quel con !<br>Bonjour Monsieur, vous cherchez quelque chose?<br>Oh, vous devez sans doute être Monsieur Hugues, j'ai une lettre à vous montrer.<br>Ummmff Avant de m'la montrer, je voudrais bien vous posez une question. A qui ai-je l'honneur ?<br>Dave, je suis le fils de Monsieur Callaghan.<br>Faites-moi voir votre papier là, Vous faites une enquête sur Georges Abitboll, l'homme le plus classe du monde.<br>Oui, vous l'avez connu vous, hein ? Humm ?",

    "Ummmfff vous savez Georges, je l'ai connu au temps du Texas. Il est encore cowboy. A l'époque j'étais moi-même cowboy. Je vivais avec Jacques, un bon copain.<br>ummfff Y avait rien de sexuel entre nous. J'vous dit ça parce qu'j'me suis souvent fait traiter de pédale, de salope. Et c'est facile de traiter les gens de pd tout ça parce que deux garçons vivent ensemble dans un ranch et portent des pantalons en cuir.<br>Bref un jour, un cavalier est arrivé à fond les ballons avec une lettre.<br>Hey les pd, y a une lettre pour vous. Tenez, bonne bourre!<br>Pov con va !",

    "Bon, y avait quoi dans cette lettre ?<br>J'en sais rien, c'est pas moi qui l'ai lu, c'est Jacques.<br>Bon ben racontez moi des choses que vous savez, pas du rien.<br>Ok ok du calme. J'sais pas ce qui y avait dans la lettre. Mais après, on est partis à cheval vers la ville de Georges.",

    "Ah j'en ai marre. Ah j'te jure, les voyages à cheval ça m'fatigue.<br>Qu'est ce que t'as ?<br>J'ai que j'commence à en avoir vraiment marre des voyages. Je rêve d'un bon bain dans une bonne aubeeeerge. Ah j'te jure, j'ai les pastèques.",

    "Yep, Yep, Yep !<br>Qu'est ce qui t'prend à dire 'Yep' comme ça ?<br>Bah, c'est pour dire 'Yep' !<br>Ah, c'est pas banal ça.<br>Chaud devant, et voilà la spécialité du chef!<br>Parfait, ça a l'air super bon.<br>Bon, maintenant qu'on est là, tu vas peut-être me dire pourquoi on est venu? Tu reçois une lettre mystérieuse et on arrive en courant.<br>J'aimerais bien savoir c'qui y avait dedans.<br>C'est une longue lettre épistolaire de mon ami Dino qui m'appelle à la rescousse pour me demander de l'aide pour Georges qui va mal.<br>Qu'est ce ça peut t'foutre, qu'il aille bien ou mal ce tâcheron. D'toute façon, j'ai jamais pu l'encadrer.",

    "Merci de m'appeler tâcheron, ça fait toujours plaisir à entendre. Surtout de la part de deux pd. Vous savez ce que vous mangez là? C'est du steak avec des boulettes entre les doigts de pied. Ça a bon goût ?<br>C'est très agréable monsieur, j'vous remercie...<br>Et la sauce, c'est de la morve séchée.<br>Et toi, tu fais chier, tu vas finir par les dégoûter.<br>Mêles-toi de tes affaires toi. Tu sais très bien que Madame Félipé, la patronne, se coupe des morceaux de nichons pour en faire des ravioles.",

    "Ah, c'est déguelasse, merde !<br>Attends, c'est censé être l'homme le plus classe. Il va sans doute nous présenter ses excuses.<br>Tu sais, tes excuses, tu peux te les coller au cul. Tout comme ton bifteck, sauf que le bifteck, ça sert à rien, le patron l'a déjà fait, il a craché dessus.<br>Ah non, pas craché. Le patron, il crache pas dans les plats.<br>Allons vieux, même dans les grands restaurants on crache dans les plats. Alors dans ce taudis, j'vois pas pourquoi ils s'feraient chier. Ah, j'vous laisse manger, bon appétit.<br>Et ben, j'ai connu un mec de droite une fois, il avait dix fois plus de classe.<br>Ah, encore une chose, j'vous conseille d'éviter la mousse au chocolat du patron.",

    "Et qu'est ce qui c'est passé après? Respirez bien..<br>Ummpffffff.. Après, tout ce que je sais, c'est que j'ai eu un accident, j'ai été blessé. Alors je me suis réveillé amnésique et j'arrivais plus à me souvenir de rien.<br>Vous avez d'autres choses à me raconter, sur Georges ?<br>Je refuse de manger des ravioles ! Mais par contre je peux vous parler de madame Félipé : elle s'est fait refaire les nichons elle. Et je sais de quoi je parle !",

    "Et Georges dans tout ça ?Ben justement, une fois, j'étais chez les indiens bilingues.<br>Salut Hugues!<br>Hello !<br>Salut Hugues, Hugues salut !<br>Salut les gars, je suis content de vous voir. Comme je passais par ici, je pensais m'arrêter un peu... à moins que vous vouliez que je parte ?<br>Tu peux rester, pas de problème ! J'suis même content qu'tu sois venu chez nous. J'aimerai bien qu'tu restes : on va manger des chips ! T'entends ? Des chips ! C'est tout s'que ça t'fait quand j'te dis qu'on va manger des chips ?? Mais qu'est ce qui t'arrives ? Pourquoi tu dis rien ? Tu fais la tronche ou quoi ?<br>Tu m'rappelles Georges, politiquement.<br>Georges ? Mais qu'est ce que j'ai à voir avec Georges ? Rien en fait, parce que si on réfléchit bien, moi je suis un vrai démocrate, Georges est un fasciste de merde ! un fasciste de merde !!<br>C'est exact, autant pour moi.",

    "Oh, et qu'est ce qu'il lui est arrivé à ce chef indien ?<br>Après, il a fait justicier dans la ville, mais aujourd'hui, il a fini de frimer. On l'a retrouvé assassiné un jour. Il en est mort !<br>Pfff ahahha. Dites moi, le numéro de votre ami Jacques, c'est bien celui qu'est noté là ?<br>Oui.<br>J'vais le donner à mes collègues, il faut qu'on l'interroge. Allo peter, prends un papier, j'vais te donner le numéro d'un certain Jacques, il faudrait l'interroger.<br>Alors c'est le 19 94 0 18 13 24 32 49 26 24 40 4 16 70933 16-4 Euh...<br>Ben, 16-4, ça fait douze.<br>Attention, y a un piège là.<br>Bon, merci, on l'appelle. Ciao.<br>Bon, on s'rappelle plus tard.",

    "Bonjour, vous êtes bien chez Steven, mais je n'suis pas là. Vous pouvez me laisser un message après le bip sonore. Merci, au revoir.<br>J'viens de recevoir un coup de téléphone de Dave, tiens c'est le numéro de Jacques.<br>Humm,Humm. Tiens regarde, ça c'est le numéro de Jacques, j'l'ai trouvé aux archives. Le numéro qu'il t'a filé Dave, c'est de la connerie. Il commence vraiment à me faire chier Dave.<br>Moi s'qui m'fait chier, c'est les effets spéciaux minables. Je supporte plus.<br>Oh ben là, j'te trouve un peu dur, on croirait entendre un pro des effets spéciaux.<br>Oh ben moi, quand tu veux. Tiens, tu connais l'effet spéciaux de la sonnette ? Dring, tiens, Dring dring-dring, tiens, et dring dring...<br>C'est super impressionnant, tu le fais bien.<br>...Et après, j'te fait dring et puis dring, et puis même encore dring oh putain j'suis crevé..<br>T'énerves pas putain.<br>Allez encore un dernier dring, maintenant t'appelle Jacques, hein !",

    "Allo monsieur Jacques ?<br>Absolument.<br>Bonjour, je vous appelle, parce que j'enquête sur Georges Abitbol, et j'aimerais beaucoup recueillir votre témoignage. C'est bon !<br>Écoutez, n'y voyez aucune mauvaise volonté de ma part, mais je tiens à vous dire que je n'ai pas beaucoup de temps. Alors pour Georges Abitbol je veux bien faire un effort, mais il faut pas me prendre pour la bonne poire.<br>J'vous remercie, vous êtes très gentil. Euh, attention, j'ai bien dit gentil, j'ai pas dit homosexuel, hein J'ai dit gentil parce que dans le témoignage de Hugues, il est noté que vous êtes parti dans la ville de Georges en ayant reçu juste une simple lettre. Qu'en est-il exactement.<br>Absolument, je pense que vous faites allusion à cette missive que nous reçûmes un jour, Hugues et moi. Cela avait l'air urgent à croire la hâte du cavalier du Poney Express. En effet, l'expéditeur avait pris soin d'écrire au dos de l'enveloppe : presse le pas facteur, car l'amitié n'attends pas.",

    "Ah j'en ai marre.<br>Tu nous fatigues, qu'est ce qui y a encore? Tu n'arrêtes pas de te plaindre.<br>J'ai faim.<br>Écoute moi bien Hugues mon ami, plus que quelques kilomètres et bientôt nous serons dans une bonne aubeeeerge. Humm, quel trouble fête.",

    "Yep, yep, yep...<br>J'vous interrompts, excusez-moi, mais cet épisode nous a déjà été raconté par Hugues. Peut-être pourriez-vous nous parlez de ce qui vous est arrivé après ce repas, dans la bonne aubeeerge, hein ?<br>Absolument, après déjeuner, il était temps que je me misse à l'ouvrage, j'allâmes voir mon ami Dino.",

    "Ohhh ben Dino, mon pauvre ami, ça n'a pas l'air d'aller bien fort. Pourquoi vous vous êtes mis dans cet état déplorable? Vous qui écrivez de si belles lettres.<br>Ça va plus du tout, j'ai plus envie de boire ni de manger, j'ai plus envie de me peigner. J'suis limite nervous break down. Oh et puis merde, j'ai même plus envie de me laver.<br>Vous n'allez pas me dire que c'est à cause de Georges quand même?<br>Georges ? Vous pouvez pas savoir, il est devenu insupportable.<br>C'est pas une raison pour plus vous laver les joues. Vous êtes malade ou quoi ? Faut arrêter !<br>S'que j'arrête, c'est les pin's vieux. Ca m'fait plus marrer.<br>Oh mais dites-moi, vous savez que vous avez l'air pitoyable. Parce que pour arrêter votre collec' ...",

    "Ça vous embête si j'regarde votre pin's là? Sheraf...Sheraf, connais pas. Parce que moi aussi, je peux m'vanter de ma collec' moi, ça fait un moment que j'l'ai et c'est pas une collec' de pd. Sauf que celui-là, je connais pas. Sheraf : inconnu au bataillon.<br>Sheraf... Tu connais pas Sheraf ? C'est un groupe ils étaient number one.<br>C'est pas une raison pour vous laisser aller et ressembler à une larve.<br>Regarde mes mains, saloperie, regarde ! Me suis niqué les mains moi avec cette saloperie de collec' de pin's à la con.<br>Bon, euh moi j'y vais, merci pour les pin's. Et vous inquiétez pas, tout va s'arranger. Et comme on dit chez nous : lehaïm.<br>Lehaïm !",


];


// Afficher le tableau
console.log(quotes);
