const quotes = [
    "Attention, ce flim n'est pas un flim sur le cyclimse, merci de votre compréhension.<br>Entre l'Australia et la South America, dans l'océan South Pacific, l'atoll de Pom Pom Galli.",

    "V12 appelle le capitaine Georges Abitbol! V12 appelle le capitaine Georges Abitbol ! Quelqu'un vous demande sur le pont.<br>Qui ?<br>Un dénommé José.<br>Ok, j'arrive V12.",

    "Ah, voilà enfin le roi de la classe, l'homme trop bien sapé : Abitbol ! Alors comme ça, t'as été élu l'homme le plus classe du monde. Laisse-moi rire, style le grand cowboy des fonds marins, genre qui fait rêver les ménagères. Sauf que moi j'les baise les ménagères. Non ? C'est pas vrai ?<br>Écoute moi bien mon p'tit José. Tu baises les ménagères, bien, tu dois avoir le cul qui brille. Mais c'est pas ça qu'on appelle la classe. J'te dis ça en qualité d'homme le plus classe du monde. <br>Hey, je t'arrête tout de suite. La classe, c'est d'être chic dans sa manière de s'habiller. Rien de tel que d'aller chez Azédin Ahlahïa ou même de s'acheter des sous-pulls, chez Ioji Yamamoto.",

    "Excuse-moi de te dire ça mon pauvre José, mais tu confonds un peu tout. Tu fais un amalgame entre la coquetterie et la classe. Tu es fou, tu dépenses tout ton argent dans les habits et accessoires de modes, mais tu es ridicule. Enfin, si ça te plait, c'est toi qui les porte. Mais moi si tu veux mon opinion, ça fait un peu 'has been'.<br>Oh la vache ! Moi ? j'ai l'air Has been ? J'en ai pour plus d'une barre de fringue sur moi, alors va te faire mettre!<br>Tu n'es vraiment pas très sympa. Mais le train de tes injures roule sur le rail de mon indifférence. Je préfère partir plutôt que d'entendre ça, plutôt que d'être sourd.<br>Bien ! Considère qu'on est plus amis ! Abitbol...",

    "Tiens regarde! les Anglais ont débarqué. On va être obligé de passer par derrière. Tu sais, par ce long tunnel tout sombre qui sent pas très bon.<br>Oh Georges, quel poète vous faites, vous me surprenez. On ne m'a jamais parlé comme ça. J'ai connu des hommes, mais jamais des comme vous.<br>Hey, tu sais à qui tu parles là ?<br>Oui !<br>Abritons nous, ça va pas tarder à péter.<br>Et encore, c'est rien.<br>Ahh bravo. Bon pousse toi, laisse moi passer.",

    "Bon V12, c'est quoi ce bordel alors ?<br>Ben ce bordel, c'est qu'il pleut comme vache qui pisse!<br>Ah bravo, merci du renseignement, heureusement qu'tu es là.<br>Mais patron...<br>Quoi 'Patron' ? Tu veux que je dise à tout le monde que ton vrai nom c'est pas V12, c'est Travers de Porc Sel Poivre ? Bon je vais chercher des serviettes éponges avec des imprimés dessus.<br>Ah celle-là... non... Celle-là... ah celle-là, ça va.",

    "Ça c'est bon, c'est épongé... Ça c'est bon, c'est réparé... Ça, ça roule... Oh putain et ça ! Faut pas laisser ça comme ça les enfants !<br>Ohh ah...<br>Georges !...Georges...Oh mon dieu Georges !<br>...ahhh... oh...<br>Aaaaaah, monde de merde.<br>Oh Georges...",

    "Et puis, je vous rappelle la principale information de cette édition : la disparition subite de Georges Abitbol qui depuis plus de quinze ans portait officiellement le titre de l'homme le plus classe du monde.<br>L'Amérique vient de perdre un de ses plus prestigieux ambassadeurs.<br>Et maintenant, un petit peu de musique avec Alain Souchon.<br>Oh non, pas lui !",

    "Bonjour patron, j'peux entrer ?<br>Ah Dave, tu tombes bien, entre. On prépare un dossier sur Georges Abitbol. Tu vas te mettre sur le coup mais tu seras pas tout seul. Tu seras avec Peter et Steven.<br>Peter et Steven... j'les aime bien. Mais pourquoi j'peux pas travailler seul ?<br>Parce que t'es trop mauvais.<br>Ah, ben là patron, vous m'avez convaincu, c'est une bonne raison. Je vais travailler avec Peter et Steven.<br>Ben alors ?<br>Ben ok, j'y vais.",

    "Ce charlot? J'savais pas qu'il existait encore.<br>Ben va falloir vous y habituez parce qu'il va travailler avec vous sur ce dossier. C'est une idée de notre ami Callaghan, une idée lumineuse.<br>Ah arrêtez vos conneries patron. C'est mon fils, mon fiston, pfff... J'sais pas pourquoi, il s'est attaché à moi. Alors, je l'aide.<br>Peut-être qu'il avait personne d'autre à qui s'attacher, mais de quoi on parle là?<br>Ben j'vais te dire de quoi on parle. Où vous en êtes avec la nécro de Georges Abitbol? Vous bossez un peu ? Humm ?<br>On vient de s'y mettre, mais on a déjà quelques p'tites idées.<br>On va interroger des tas de gens. Tout ceux qui l'ont aimé, qui l'ont haï, bref tout ceux qui l'ont approché et qui l'ont connu. Ça fait déjà du boulot.",

    "Quoi d'autre?<br>Et puis, c'est pas tout !<br>Oui, on a pensé qu'on devrait expliquer ses dernières paroles.<br>'Monde de Merde' Vous avez raison.<br>Ouais, on en a chié pour trouver c'te idée. On était charette.<br>L'homme le plus classe du monde meurt, et ses dernières paroles c'est 'monde de merde'. Pourquoi il a dit ça ? C'est ce que j'veux savoir!<br>Merci, c'est pas facile à trouver. C'est sûrement un nom, si c'est une femme, je veux savoir quelle femme. Si c'est un cheval, je veux savoir dans quelle course!<br>Nous, on pensait que ça pouvait être un traîneau.",

    "Bonjour, c'est moi Orson Welles. Ceci est ma maison que vous voyez derrière là. Pas mal non? C'est Français.<br>Je m'permets d'interrompre ce flim parce qu'on s'fout un peu de ma gueule. C'est du vol et du plagiat.<br>J'aime pas trop les voleurs et les fils de pute. Dans ce flim, le héros meurt au début et des journalistes décident d'enquêter sur ses dernières paroles... Comme dans Citizen Kane.<br>J'appelle ça du plagiat. Les journalistes vont interviewer des gens sur le héros. Vous allez voir que les témoignages, ça va être des flashbacks. J'le vois trop arrivé.<br>Aaaaaah... rosebud !",

    "Bon, et à part ça ?<br>Ben, à part ça, on est un peu coincés, on a pas l'ombre d'une piste.<br>Vous savez qu'il a vécu au Texas la moitié de sa vie. Faut chercher par là.<br>'Faut chercher par là', 'faut chercher par là', vous êtes gonflé vous, 'faut chercher par là'.<br>Bravo, quel enthousiasme.<br>Mais au fait, j'y pense : Callaghan, il devrait pouvoir vous aider depuis le temps qu'il est là payé à rien foutre. Autant qu'il serve à quelque chose, ce gros porc.<br>J'suis peut-être payé à rien foutre, mais mes tuyaux, j'les garde pour mon fils.<br>Ah, eh oh la honte!...<br>Mais comprenez moi mes amis, c'est mon fils, ma bataille, c'est le fruit de mes entrailles quoi. J'avais un nom, une adresse, ben j'lui ai donné.<br>Oh le lourd.<br>On dirait que ça vous emmerde, je m'trompe ?",

    "Connasse.<br>C'est vous qui m'avez traité de connasse ?<br>Mais non.<br>Vous savez, c'est pas très agréable.<br>Bonjour, je viens voir un certain Monsieur Hugues.<br>Hey, c'est quoi ça ?<br>Oh va te faire foutre !<br>Vous dites que j'aille me faire foutre? Ok, j'y vais.<br>Pff quel con !<br>Bonjour Monsieur, vous cherchez quelque chose?<br>Oh, vous devez sans doute être Monsieur Hugues, j'ai une lettre à vous montrer.<br>Ummmff Avant de m'la montrer, je voudrais bien vous posez une question. A qui ai-je l'honneur ?<br>Dave, je suis le fils de Monsieur Callaghan.<br>Faites-moi voir votre papier là, Vous faites une enquête sur Georges Abitboll, l'homme le plus classe du monde.<br>Oui, vous l'avez connu vous, hein ? Humm ?",

    "Ummmfff vous savez Georges, je l'ai connu au temps du Texas. Il est encore cowboy. A l'époque j'étais moi-même cowboy. Je vivais avec Jacques, un bon copain.<br>ummfff Y avait rien de sexuel entre nous. J'vous dit ça parce qu'j'me suis souvent fait traiter de pédale, de salope. Et c'est facile de traiter les gens de pd tout ça parce que deux garçons vivent ensemble dans un ranch et portent des pantalons en cuir.<br>Bref un jour, un cavalier est arrivé à fond les ballons avec une lettre.<br>Hey les pd, y a une lettre pour vous. Tenez, bonne bourre!<br>Pov con va !",

    "Bon, y avait quoi dans cette lettre ?<br>J'en sais rien, c'est pas moi qui l'ai lu, c'est Jacques.<br>Bon ben racontez moi des choses que vous savez, pas du rien.<br>Ok ok du calme. J'sais pas ce qui y avait dans la lettre. Mais après, on est partis à cheval vers la ville de Georges.",

    "Ah j'en ai marre. Ah j'te jure, les voyages à cheval ça m'fatigue.<br>Qu'est ce que t'as ?<br>J'ai que j'commence à en avoir vraiment marre des voyages. Je rêve d'un bon bain dans une bonne aubeeeerge. Ah j'te jure, j'ai les pastèques.",

    "Yep, Yep, Yep !<br>Qu'est ce qui t'prend à dire 'Yep' comme ça ?<br>Bah, c'est pour dire 'Yep' !<br>Ah, c'est pas banal ça.<br>Chaud devant, et voilà la spécialité du chef!<br>Parfait, ça a l'air super bon.<br>Bon, maintenant qu'on est là, tu vas peut-être me dire pourquoi on est venu? Tu reçois une lettre mystérieuse et on arrive en courant.<br>J'aimerais bien savoir c'qui y avait dedans.<br>C'est une longue lettre épistolaire de mon ami Dino qui m'appelle à la rescousse pour me demander de l'aide pour Georges qui va mal.<br>Qu'est ce ça peut t'foutre, qu'il aille bien ou mal ce tâcheron. D'toute façon, j'ai jamais pu l'encadrer.",

    "Merci de m'appeler tâcheron, ça fait toujours plaisir à entendre. Surtout de la part de deux pd. Vous savez ce que vous mangez là? C'est du steak avec des boulettes entre les doigts de pied. Ça a bon goût ?<br>C'est très agréable monsieur, j'vous remercie...<br>Et la sauce, c'est de la morve séchée.<br>Et toi, tu fais chier, tu vas finir par les dégoûter.<br>Mêles-toi de tes affaires toi. Tu sais très bien que Madame Félipé, la patronne, se coupe des morceaux de nichons pour en faire des ravioles.",

    "Ah, c'est déguelasse, merde !<br>Attends, c'est censé être l'homme le plus classe. Il va sans doute nous présenter ses excuses.<br>Tu sais, tes excuses, tu peux te les coller au cul. Tout comme ton bifteck, sauf que le bifteck, ça sert à rien, le patron l'a déjà fait, il a craché dessus.<br>Ah non, pas craché. Le patron, il crache pas dans les plats.<br>Allons vieux, même dans les grands restaurants on crache dans les plats. Alors dans ce taudis, j'vois pas pourquoi ils s'feraient chier. Ah, j'vous laisse manger, bon appétit.<br>Et ben, j'ai connu un mec de droite une fois, il avait dix fois plus de classe.<br>Ah, encore une chose, j'vous conseille d'éviter la mousse au chocolat du patron.",

    "Et qu'est ce qui c'est passé après? Respirez bien..<br>Ummpffffff.. Après, tout ce que je sais, c'est que j'ai eu un accident, j'ai été blessé. Alors je me suis réveillé amnésique et j'arrivais plus à me souvenir de rien.<br>Vous avez d'autres choses à me raconter, sur Georges ?<br>Je refuse de manger des ravioles ! Mais par contre je peux vous parler de madame Félipé : elle s'est fait refaire les nichons elle. Et je sais de quoi je parle !",

    "Et Georges dans tout ça ?Ben justement, une fois, j'étais chez les indiens bilingues.<br>Salut Hugues!<br>Hello !<br>Salut Hugues, Hugues salut !<br>Salut les gars, je suis content de vous voir. Comme je passais par ici, je pensais m'arrêter un peu... à moins que vous vouliez que je parte ?<br>Tu peux rester, pas de problème ! J'suis même content qu'tu sois venu chez nous. J'aimerai bien qu'tu restes : on va manger des chips ! T'entends ? Des chips ! C'est tout s'que ça t'fait quand j'te dis qu'on va manger des chips ?? Mais qu'est ce qui t'arrives ? Pourquoi tu dis rien ? Tu fais la tronche ou quoi ?<br>Tu m'rappelles Georges, politiquement.<br>Georges ? Mais qu'est ce que j'ai à voir avec Georges ? Rien en fait, parce que si on réfléchit bien, moi je suis un vrai démocrate, Georges est un fasciste de merde ! un fasciste de merde !!<br>C'est exact, autant pour moi.",

    "Oh, et qu'est ce qu'il lui est arrivé à ce chef indien ?<br>Après, il a fait justicier dans la ville, mais aujourd'hui, il a fini de frimer. On l'a retrouvé assassiné un jour. Il en est mort !<br>Pfff ahahha. Dites moi, le numéro de votre ami Jacques, c'est bien celui qu'est noté là ?<br>Oui.<br>J'vais le donner à mes collègues, il faut qu'on l'interroge. Allo peter, prends un papier, j'vais te donner le numéro d'un certain Jacques, il faudrait l'interroger.<br>Alors c'est le 19 94 0 18 13 24 32 49 26 24 40 4 16 70933 16-4 Euh...<br>Ben, 16-4, ça fait douze.<br>Attention, y a un piège là.<br>Bon, merci, on l'appelle. Ciao.<br>Bon, on s'rappelle plus tard.",

    "Bonjour, vous êtes bien chez Steven, mais je n'suis pas là. Vous pouvez me laisser un message après le bip sonore. Merci, au revoir.<br>J'viens de recevoir un coup de téléphone de Dave, tiens c'est le numéro de Jacques.<br>Humm,Humm. Tiens regarde, ça c'est le numéro de Jacques, j'l'ai trouvé aux archives. Le numéro qu'il t'a filé Dave, c'est de la connerie. Il commence vraiment à me faire chier Dave.<br>Moi s'qui m'fait chier, c'est les effets spéciaux minables. Je supporte plus.<br>Oh ben là, j'te trouve un peu dur, on croirait entendre un pro des effets spéciaux.<br>Oh ben moi, quand tu veux. Tiens, tu connais l'effet spéciaux de la sonnette ? Dring, tiens, Dring dring-dring, tiens, et dring dring...<br>C'est super impressionnant, tu le fais bien.<br>...Et après, j'te fait dring et puis dring, et puis même encore dring oh putain j'suis crevé..<br>T'énerves pas putain.<br>Allez encore un dernier dring, maintenant t'appelle Jacques, hein !",

    "Allo monsieur Jacques ?<br>Absolument.<br>Bonjour, je vous appelle, parce que j'enquête sur Georges Abitbol, et j'aimerais beaucoup recueillir votre témoignage. C'est bon !<br>Écoutez, n'y voyez aucune mauvaise volonté de ma part, mais je tiens à vous dire que je n'ai pas beaucoup de temps. Alors pour Georges Abitbol je veux bien faire un effort, mais il faut pas me prendre pour la bonne poire.<br>J'vous remercie, vous êtes très gentil. Euh, attention, j'ai bien dit gentil, j'ai pas dit homosexuel, hein J'ai dit gentil parce que dans le témoignage de Hugues, il est noté que vous êtes parti dans la ville de Georges en ayant reçu juste une simple lettre. Qu'en est-il exactement.<br>Absolument, je pense que vous faites allusion à cette missive que nous reçûmes un jour, Hugues et moi. Cela avait l'air urgent à croire la hâte du cavalier du Poney Express. En effet, l'expéditeur avait pris soin d'écrire au dos de l'enveloppe : presse le pas facteur, car l'amitié n'attends pas.",

    "Ah j'en ai marre.<br>Tu nous fatigues, qu'est ce qui y a encore? Tu n'arrêtes pas de te plaindre.<br>J'ai faim.<br>Écoute moi bien Hugues mon ami, plus que quelques kilomètres et bientôt nous serons dans une bonne aubeeeerge. Humm, quel trouble fête.",

    "Yep, yep, yep...<br>J'vous interrompts, excusez-moi, mais cet épisode nous a déjà été raconté par Hugues. Peut-être pourriez-vous nous parlez de ce qui vous est arrivé après ce repas, dans la bonne aubeeerge, hein ?<br>Absolument, après déjeuner, il était temps que je me misse à l'ouvrage, j'allâmes voir mon ami Dino.",

    "Ohhh ben Dino, mon pauvre ami, ça n'a pas l'air d'aller bien fort. Pourquoi vous vous êtes mis dans cet état déplorable? Vous qui écrivez de si belles lettres.<br>Ça va plus du tout, j'ai plus envie de boire ni de manger, j'ai plus envie de me peigner. J'suis limite nervous break down. Oh et puis merde, j'ai même plus envie de me laver.<br>Vous n'allez pas me dire que c'est à cause de Georges quand même?<br>Georges ? Vous pouvez pas savoir, il est devenu insupportable.<br>C'est pas une raison pour plus vous laver les joues. Vous êtes malade ou quoi ? Faut arrêter !<br>S'que j'arrête, c'est les pin's vieux. Ca m'fait plus marrer.<br>Oh mais dites-moi, vous savez que vous avez l'air pitoyable. Parce que pour arrêter votre collec' ...",

    "Ça vous embête si j'regarde votre pin's là? Sheraf...Sheraf, connais pas. Parce que moi aussi, je peux m'vanter de ma collec' moi, ça fait un moment que j'l'ai et c'est pas une collec' de pd. Sauf que celui-là, je connais pas. Sheraf : inconnu au bataillon.<br>Sheraf... Tu connais pas Sheraf ? C'est un groupe ils étaient number one.<br>C'est pas une raison pour vous laisser aller et ressembler à une larve.<br>Regarde mes mains, saloperie, regarde ! Me suis niqué les mains moi avec cette saloperie de collec' de pin's à la con.<br>Bon, euh moi j'y vais, merci pour les pin's. Et vous inquiétez pas, tout va s'arranger. Et comme on dit chez nous : lehaïm.<br>Lehaïm !",

    "Bonsoir!<br>Pd!<br>Oh, c'est pas banal.<br>Ça commence à être pesant cette histoire de pd, tout le monde s'acharne sur nous, alors qu'on est même pas pd.<br>Mais oui, je sais. T'inquiète pas j'vais aller le voir dès demain Georges.<br>Allez bonne nuit, dors bien.",

    "Georges, il faut que je vous parle. Je sais très bien que sous prétexte que je suis gentil, les gens me prennent souvent pour un truffon. Soit, j'en prends mon parti. N'empêche, je crois qu'on a parlé. Visiblement, vous n'allez pas bien, laissez-moi vous aider.<br>Casse-toi Jacques !<br>Oh ça mais vous refusez le dialogue?<br>Exactement j'veux pas qu'on parle, j'veux que tu quittes la ville. Et t'as intêret à te casser avant 9 heures.<br>Mais Georges, rassurez moi : vous seriez pas un peu en train de me prendre pour un con des fois ?<br>Si complètement même. Et casse-toi maintenant.<br>Georges, vous me décevez, je m'attendais à plus d'ouverture d'esprit de votre part. Je vous aiderez malgré vous.",

    "Rester en ville malgré les menaces, j'trouve ça drolement courageux de la part d'un pd comme vous.<br>Hey,bon c'est fini oui, ça , c'est une rumeur, j'ai jamais été homosexuel, et encore moins pédéraste.<br>C'est fou que vous ayez tant de complexes.<br>Allez dites le que vous êtes pd !<br>Avouez, vous êtes en train de choper la honte.<br>Et quand bien même j'serai homo, j'vois pas ce que ça change.<br>En string vous devez être bonne.",

    "Soit prêt,c'est bientôt l'heure. ... Cigarette?<br>Bon très bien, j'vais tout vous dire puisque ... Oh, il est 9 heures !<br>Ohlala 9 heures !!<br>Il est déjà 9 heures, là ?<br>Sur mon front y a pas marqué radio-réveil.<br>À part ça, vous avez la classe !<br>Tu vas voir la classe... oh putain de zen, Nar deen ..<br>Où ça nous mène la folie des hommes? On court tout droit à notre perte.<br>Hey patron, j'ai trouvé de la dynamite !<br>Ça me donne une idée.<br>Hey les minables, y a pas qu'moi qui suis pd, y en a un autre : il s'appelle Geooorge.<br>C'est ça, cause cause.... Salaud !<br>Et toi, sale parasite, casse-toi !<br>Ça, il va le payer !<br>Ouais.",

    "Il devait être nerveux le Georges pour s'énerver comme ça.Vous voulez que je vous raconte la fin de l'histoire ?<br>Oui s'il vous plaît monsieur. J'imagine que vous avez dû appeler la police, vous étiez dans votre droit après tout.<br>Pas du tout, nous avons réglé cette histoire entre hommes.<br>Ah bon ?<br>Absolument. Voyez-vous, Hugues fut gravement blessé. Georges est venu s'excuser immédiatement.<br>Georges? S'excuser ? Immédiatement ?<br>Absolument.<br>Quelle classe!<br>Absolument.",

    "Hugues, j'ai su qu't'étais blessé, je suis venu m'excuser.<br>Il fallait y penser avant, au lieu de venir pleurer dans ma chambre.<br>Ouais c'est vrai, c'est minable, c'est tout moi ça. Mais j'espérais tout de même te faire plaisir.<br>Mon plus grand plaisir serait qu'tu te calmes, gros blaireau!<br>Et oui... j'm'énerve.",

    "Ah pardon, si j'résume votre histoire : Georges n'a eu qu'à vous faire un mea culpa. dites, vous êtes drôlement gentil vous.<br>Arrêtez de dire ça. Je n'suis pas gentil. C'est pas vrai, quand je m'énerve, je me mets dans des états dingues, je suis méconnaissable.<br>Ok, excusez moi. J'peux vous poser une dernière question ?<br>Absolument.<br>Voilà, à quoi vous pensez si j'vous dit : 'monde de merde' ?<br>Au revoir.",

    "Pourquoi t'as choisi de faire ce boulot là toi ?<br>Ben si j'fais journaliste, c'est évidemment pour être célèbre. Moi j'veux être connu, tu sais pourquoi ? Pour niquer les gonzesses. Quand t'es célèbre, tu niques plein de gonzesses. Et puis aussi tu bouffes des trucs bien meilleurs qu'ici.<br>Moi pour les gonzesses, je suis super d'accord avec toi. Mais pour la bouffe, je vois pas c'que tu veux dire. T'aurais envie de manger quoi exactement <br>Ben je sais pas, par exemple, une quiche lorraine.<br>Une ouiche.<br>Une quoi ?<br>On dit une ouiche lorraine.<br>T'es sûr? Ca fait bizarre ouiche lorraine.",

    "Bon, on va où là ?<br>Ben, on va voir Dino, le mec qui a écrit la lettre à Jacques.<br>Eh attention, mais quels connards ces piétons!<br>Ouais.<br>Qu'est-ce que tu disais là ?<br>Hein ? Oh rien rien, des conneries, laisse tomber.<br>Je sais toi, mais moi le mystère s'épaissit.",

    "Messieurs, permettez-moi de vous souhaiter la bienvenue. D'ailleurs, il faut pas rester debout, asseyez vous, mettez-vous à l'aise.<br>Merci m'sieur, c'est très gentil.<br>C'est une leçon de savoir vivre.<br>C'est naturel, mais dites moi plutôt c'que j'peux faire.<br>Oui, alors voilà, nous sommes journalistes et nous voudrions savoir où vous avez connu Georges...Georges Abitbol.<br>Où j'ai connu Georges? C'est une excellente question... À la ferme.<br>La ferme? Quelle ferme?<br>À la ferme ta gueule toi du con, espèce de crétin ! Qu'est ce que tu veux, nous prendre la tête là ? pauv' con ! Oui j'l'ai connu à la ferme, on était des cow boy, on vivait à la ferme, ça n'a rien d'étonnant.<br>Merci, c'est très agréable. Non mais c'est vrai, je me fais engueuler devant des journalistes qu'on connait même pas. C'est classe bravo.<br>Oh ça va ? on vous fait pas chier là ? Non c'est sûr, non je rêve.",

    "Dites moi, vous avez envoyé une lettre à Jacques il me semble. C'était quoi cette lettre?<br>Et bien c'est lettre, c'est vraiment très simple. J'avais un problème avec Georges, j'ai écrit à mon vieil ami Jacques. Mais si vous le voulez bien, j'vais tout vous raconter depuis le début. Vous savez, j'arrivais d'Italie, de Turin. À l'époque, j'étais supporter de la Juventus.",

    "Ok j'arrive, mais arrête de tirer sur oim !<br>Mouais, viens ici... Qu'est ce que tu fous avec les bras en l'air, j't'ai dit d'les lever ? Baisse tes bras ! C'est moi qui les lève.<br>Ah non, c'est à moi d'les lever.<br>Non, c'est à moi d'les lever, c'est moi qui décide. Et puis d'ailleurs, arrête de faire tout comme moi. Baisse les bras et prend ton flingue au lieu d'être là à m'copier.<br>Mon flingue ? Avec plaisir!<br>Tout compte fait, j'préfère garder mon flingue, désolé. Et j'vais partir avec mon cheval, vieux!<br>Y a pas de problème, comme tu veux. J'vais juste le préparer pour toi.<br>Non j'ai changer d'avis : tu prends le cheval, et tu te casses!<br>Ok.<br>Putain, j'me suis mal démerdé. Pourtant j'ai pas fait une concession.",

    "Le temps a passé, je pensais ne plus jamais revoir ce type, mais un an après, nos chemins se sont croisés une nouvelle fois. Je fréquentais alors un bar que le patron, un certain Bazounga, avait intelligemment appellé : le Orlandoz.",

    "Mais j'te reconnais toi, j't'ai déjà vu quelque part, je suis sûr que j'te reconnais.<br>Désolé, mais c'est moi qui te reconnais, j't'ai vu le premier, toi tu m'as vu en deuxième, vu ?<br>Bon, j't'ai vu le deuxième alors voilà.<br>Perdu, c'est aussi moi qui t'ai vu le deuxième.<br>Oh, dis donc : t'es super fort !<br>Mais j'suis pas super fort, j'suis mieux que ça même, j'suis surpuissant!<br>Bon, ben lui il va me prendra la tête.<br>Ça fait plusieurs fois que j'te croise, t'es toujours sur mon chemin. Tu veux quoi ?<br>Mais c'est peut-être toi qui est sur mon chemin, pas moi.<br>C'est pas mal ça, le pin's sur la cravate.<br>C'est la classe.",

    "Mais au fait, toi ? D'où tu viens ? <br>Moi j'suis juif.<br>T'es juif toi ?<br>Oh oui je suis juif, et si tu veux tout savoir, j'suis même juif arabe.<br>Juif arabe ? Humm. Je préfère les sépharates tu sais. A mon avis, juif et arabe, c'est bizarre. Moi j'aime pas les gens bizarres.<br>Oh merde, j'peux pas encadrer les nazis, mais laisse tomber.<br>Précise ta pensée.<br>Pour être tout à fait exact...Je pense que t'es un ouf toi! un ouf malade. En plus, c'est du racisme.<br>Ça c'est ton opinion personnelle, que je suis raciste. Si tu veux mon avis, si y a un raciste ici, c'est oit !<br>De toute façon, ça sert à rien de discuter avec toi, t'as toujours raison.<br>Si ça sert de discuter ! C'est toi qui a toujours raison.",

    "Qu'est ce que j'apprends Franckie ? Espèce de malhonnête ! Il parait que t'as des propos intolérables, où y a pas de tolérance. Tu sais donc pas que c'est pas bien d'être raciste ? Que c'est mal ? On ne doit pas faire de discrimination raciale, c'est mal ! Juger les gens sur leur religion, c'est mal, sur leur couleur de leur peau, sur leur origine sociale ou sur leur nationalité, c'est mal.<br>Ok, puisque je vois qu'on ne peut pas discuter, on va faire un duel.<br>Oh .. .ohhohh ...<br>Enculé de ta race !",

    "J'adore les duels inoffensifs. Et maintenant casse-toi ! Et la prochaine fois, je m'occuperai de toi avec de vraies balles. Et ça chauffera pour ton cul, sale français.<br>Bah, j'suis même pas français, j'suis américain.<br>Non, t'es français, moi j'suis américain!",

    "Et voilà, c'est pour ça que je l'ai appelé mon vieil ami Jacques. Je veux pas dire, mais c'est un mec qui a vraiment plein de qualité.<br>Mouais moi j'me demande quand même s'il était pas un peu con.<br>Parlez-nous du contenu de cette lettre.<br>Oui, s'il vous plaît, à moins que ce soit privé, et que vous ayez des principes.<br>Mais c'est privé et j'ai des principes. Mais comme vous m'êtes sympathiques, j'vais vous raconter s'qui y avait dans la lettre.<br>Merci, c'est gentil à vous.<br>Y a pas de mal, vous m'êtes sympathiques.",

    "C'était un soir, j'avais le spleen, le blues.<br>Mon cher Jacques, je vous écris parce que j'ai besoin de vous. C'est Georges qui a besoin d'aide. Il ne supporte plus la vie au Texas, pas de clim' quand il fait chaud. Pas de téléphone, pas de télé, pas de chauffage : bref il supporte mal de n'pas avoir une vie moderne. Ça le rend irritable. Hier...",

    "Bonsoir Georges, j'aimerais beaucoup vous parler.Si tu veux m'parler, envoie-moi un…. fax !<br>Un fax, non mais des fois, faut vraiment qu'il aille mal. Et en plus, avant c'était pas comme ça. Avec Georges, je m'souviens, on restait des après midi entières à rester dans notre chambre à s'chamailler gentiment, à se raconter des souvenirs.",

    "Tu veux que j'te raconte un souvenir ?<br>Un souvenir? Oh oui.<br>Oh laisse tomber, tu t'fous de ma gueule ?<br>Oh non j'me fous pas de votre gueule, jamais de la vie.<br>Et ben j'vais te raconter l'histoire de ce malade qui s'est pointé un soir dans ma chambre d'hôtel, un putain d'énergumène.<br>Bonsoir, qu'est ce que vous faites dans ma chambre ? Vous avez un truc à me demander ?<br>Aime-moi tendre, aime-moi vrai !<br>Ça veut dire quoi ces conneries ?<br>Ça veut dire : aime moi tendre et aime moi vrai.<br>Moi ce qu'j'vois c'est que dans deux secondes, j'vais te botter le cul !<br>Bon, écoute, tu peux faire ce que tu veux, mais évite de marcher sur mes chaussures en suédines bleues.<br>C'est quoi ça ?<br>Ne sois pas cruel. Un pour l'argent, deux pour le spectacle, et trois pour le cailloux.<br>Et voilà c'était mon souvenir, En tout cas, s'il cherchait pour du trouble, il est venu à la bonne place.",

    "Voilà, malheureux aujourd'hui, c'est bien fini : Georges n'est plus le même homme. C'est pourquoi vous devez venir mon cher Jacques.<br>Et voilà, je pense que maintenant, vous voyez mieux le type de problème que j'avais avec Georges et pourquoi j'ai écrit cette lettre.",

    "Tu peux m'dire ce qu'on fait dans ce flim Bob ?<br>Oui j'pourrais, mais d'abord faut sucer... Oh ça va, j'plaisantais, détends-toi. On a rien à faire là, ça doit être une erreur dans l'enchaînement des flashbacks. Ça ne devrait pas trop durer.<br>Ça m'a l'air d'un bordel.<br>Attention, on tourne à droite...1 2 3. Restabilisation. Attention, on va plonger... <br>Immersion de l'astronef.",

    "P'tain, j'ai un de ces mal de bide moi. Ça c'est le hamburger ça. J'arrive pas à le digérer. T'avais raison, on aurait dû prendre une ouiche lorraine.<br>Moi j'suis sûr qu'on dit quiche. Enfin bon...<br>M'emmerde pas avec tes histoires, j'te dis que j'ai mal au bide. J'ai la méga chiasse, putain, la méga chiasse.<br>Ben, excuse-moi.<br>'Excuse-moi', mal au bide ! Tu sais ce que c'est ? Faut que j'aille chier, bordel ! Faut que j'aille chier, faut que j'aille chier, rapidos !!",

    "Alors une : tu poses mon bouquin d'exercices isométriques tout de suite. Merci. Et deux : on pourrait savoir c'que tu fais dans mon bureau s'te plait ?<br>Rien, à part que j'viens d'avoir une information qui mérite la une. La mort de Georges n'était pas accidentelle, il s'est fait assassiné.<br>Et on peut savoir comment tu sais ça ?<br>Ah ben c'est très simple, j'ai eu le tuyau par un dénommé Gorge Profonde.<br>Ah ben merde alors ! Gorge Profonde, mais c'est incroyable ça.<br>Moi maintenant de toute façon, j'ai fait avancer l'enquête.<br>Et on peut savoir : ça veut dire quoi ça ?<br>Rien, à part que toi et ton copain Peter, vous êtes un peu à la rue.<br>Et mais t'es un minable! Et tu te crois le meilleur journaliste du monde, c'est incroyable ça.<br>Meilleur journaliste du monde... Incroyable ça.",

    "Bon maintenant t'arrêtes... Parce que j'te f'rais dire que pendant qu'on parle, Peter, il a la méga chiasse, alors un peu d'dignité s'te plait ! Ah et puis, j'voulais te dire un truc à propos de Gorge Profonde : c'est mon indicateur, alors touche à ton cul !<br>Excusez-moi messieurs, Peter, il fait du boucan dans les waters.<br>Ouahou... Steven ! Tu vas pas me croire, j'ai plus mal au bide, je suis guéri. Par contre, on ne peut plus rentrer dans les chiottes, y en a partout!<br>Merde, allez !",

    "Patron ! Patron ! On a un problème, il faut qu'on vous parle.<br>Du dossier Georges Abitbol ?<br>Non, des chiottes, Peter les a bouchées.<br>Ce n'est pas de ma faute, patron, j'étais malade.<br>Ça doit être les burgers.",

    "Allo Peter ? C'est Steven. Alors note bien ce que j'vais te dire. Tu vas aller interroger un certain José.<br>Noter... dire... interroger... José.<br>Par contre, il ne supporte pas les journalistes...c'est bon là, tu notes là ?<br>Ben oui, je note... alors ?<br>Donc, vu que s'il sait que t'es journaliste, il te recevra pas.<br>S'il sait ... journaliste... pas...<br>Ce que tu vas faire, c'est que tu vas te déguiser.<br>Ce que j'vais faire.... déguiser..<br>T'as tout compris ?<br>Oui, mais mon téléphone il marche pas.<br>Et tu vas te déguiser comment ?<br>Ah j'sais pas encore.<br>T'as intérêt de trouver un truc bien. Non mais j'te fais confiance.<br>T'inquiètes, j'vais trouver un truc bien.",

    "Un Restaurant Mexican Food... Zeb! c'est pas vrai.<br>Buenas noches.<br>Hey, mais tu parles espagnol.<br>Un poquito.<br>Hey ! Tu crois que tu m'impressionnes ? Moi je sais dire : Allons à la plage monsieur le renard. Vamos à la playa, senor Zorro. Est-ce que tu aimerais te baffrer un chili con carne ?<br>Non merci, je... je suis un peu ballonné, là. Je ne suis pas trop bien.<br>Hummm.<br>J'suis désolé, hein? Y a pas d'offense. Par contre, la prochaine fois, avec plaisir. Un bon chili con carne, d'habitude, j'suis partant. Mais là je fais un régime, à base de ... à base de ouiche lorraine.<br>Excuse-moi ? À base ?<br>À base de ouiche lorraine... C'est des p'tites tartes.",

    "Et non mais pour qui tu m'prends ? Je rêve ! La fromagerie en bas de chez moi, elle vendait trois choses : du fromage, des ouiches lorraines et de la bouche chinoise. Alors toi mec, avec tes régimes à la con, tu m'fais bien marrer ! T'as devant toi le spécialiste de la ouiche lorraine. Le spécialiste des travers de porcs sel-poivre. A 23 ans j'ai gagné le concours du meilleur cuisinier asiatique en leur préparant un... méchoui.<br>Un méchoui ? Tu pipotes pas un peu toi ?<br>Jamais j'pipote !<br>Et bien puisque c'est ça, parle moi de Georges Abitbol.<br>Georges Abitbol s'était loin d'être un pérave. Jamais il se s'rait vanté comme je viens de le faire sur la cuisine : humainement, il avait la classe. Moi j'préfèrerais avoir sa classe plutôt qu'avoir la mienne. Moi j'suis un peu just'.<br>Vous l'aimiez bien ?<br>Oui, oh laissez moi.<br>Hey la choucroute, si tu veux une saucisse ?",

    "C'est trop bien de se déguiser.<br>Mouais...<br>Non non, j't'assure.<br>Abitbol... Georges Abitbol... Classe man, top of the pop ! A disparu, poil au cul. Au large du port de Valparaiso. Ah c'est beau. Mais tout ça nous éloigne de Georges. Ouapapapadou waa Angoisse, fausse angoisse. J'ai plus de repère, pour l'instant.. wadoudadoudou.<br>Steven, arrêtes s'te plait, j'ai jamais pu encadrer Michel Legrand.<br>D'accord, d'accord, chabouda doudiiii<br>J'aime pas comme tu conduis, j'sais pas j'ai pas confiance.<br>Tais-toi, tu m'empêches de me concentrer.<br>Quand j'serai célèbre, je m'ferai des meufs... je ferai des folies... tableubleubleuaaa<br>Steven, arrête toi, c'est insupportable.<br>Hummm HUM HUM HUmm!!!",

    "Tu sais à propos de Steven, c'est encore plus balaise que moi avec mon déguisement. Il traverse tout le pays pour une interview. Mais lui, il se met vraiment dans la peau du personnage.<br>J'trouve ça vraiment courageux de traverser l'Amérique de fond en comble... à pied.<br>C'est du journaliste total.<br>Hey, il passe par l'Alaska ce con.<br>En plus, monter à pied là haut.. putain, faut être con !<br>Ben tu vois moi, par exemple, autant au début j'trouvais ça con de s'déguiser, autant maintenant, vous m'avez donné envie. Sauf que moi, on va pas me reconnaitre, c'est comme ça : un vrai p'tit caméléon le Dave. Tu trouves pas que j'me suis musclé ces derniers temps ? Tu veux voir mon déguisement ?<br>Tu sais, faut le voir porter. T'as déjà entendu parler d'Artémus Gordon ? J'pense que tu peux faire beaucoup mieux qu'une simple chemise.",
    
    "Ah, ça c'est à peine croyable. J'me trouve un panoplie super bien, pffaa ... Une chemise dont j'suis hyper fier. Et voilà comment on le félicite le Dave!<br>Excuse-moi, mais là j'pense à Steven. J'me dis qu'il a beau être à pied, il doit surement vivre des moments extraordinaires.<br>Mon cher Peter, ça y est j'y suis. Même si mon déguisement n'est pas encore tout à fait fini : la casquette ainsi que les bottes ne me conviennent qu'à moitié. Je sens grandir en moi la flamme qui a dû animer les grands reporters de ce siècle. Je pense à Albert Londres, Günter Wallraff, et autre Robert Namias!",

    "Entrez !<br>Bonjour Monsieur, je suis journaliste et je fais une enquête sur la mort de Georges Abitbol. Je sais que vous avez vécu au Texas, je voudrais recueillir votre témoignage.<br>Ah, je vous arrête tout de suite, il doit y avoir erreur sur la personne : je n'ai jamais mis les pieds au Texas.<br>Laissez tomber votre cinéma avec moi, je sais que vous y étiez.<br>Ok c'est bon. Mais alors il faut que je vous dise : je ne me souviens plus de grand-chose. À vrai... À vrai dire, j'ai quelques souvenirs très confus, des visages comme ça, qui me reviennent de temps à autres. Je me souviens surtout d'odeurs, de sensations plus que d'anecdotes précises. D'autant plus que je ne suis pas resté longtemps au Texas. En fait, je n'vois pas ce que j'pourrais vous raconter si ce n'est deux ou trois vagues choses qui n'ont guère d'intérêt pour un journaliste. Alors une : je m'en souviens pas, deux : je n'suis pas resté longtemps et cinq : y a pas de cinq.",

    "Mon cher Peter, me voici en Alaska, malgré le froid, malgré une mule impôtante, malgré ma fausse barbe qui me gratte, je continue à croire en mon aventure. J'ai quand même deux ou trois doutes.",

    "Ben tu vois Dave, il commence à ressembler à quelque chose ton déguisement. Seulement, avec ta tête de français, là vraiment j'suis pas sûr. Y’a beaucoup de boulot avant de faire comme Steven, lui c'est le meilleur.<br>J'vais la métamorphoser ma tête de français. Tu vas voir, tu vas pas en croire tes yeux. D'ailleurs, moi aussi j'vais au Texas, récolter deux ou trois témoignages. Sauf que moi, j'suis pas comme Steven, je prends l'avion.",

    "Mon cher Peter, j'ai perdu beaucoup de temps avec le blizzard, je crois bien que j'ai pris froid.<br>Alors les bouseux? Qui va me parler de Georges, qui c'est qui va tout dire à Dave ? Bon, toi tu dis rien, c'est normal t'es une croix en bois, t'as qu'à te taire.<br>Meuh !<br>Ah voilà enfin quelqu'un qui va peut être me dire quelque chose?<br>Meuuuuuh !<br>Ok, tu veux pas me parler humm? Tu veux que j'fasse parler la poudre ?<br>À mon avis, tu m'prends pour un con. Tu m'as l'air bien jeune pour avoir connu cette époque, une vachette comme toi. Ça sent le pipo ton histoire... Le pipo !",

    "Mon cher Peter, me voilà dans le désert. J'ai un nouvel ami, il me suit partout, mais il est un peu con. Tu me diras : il a 5 ans. J'me sens seul.",

    "Écoutez, on m'l'a dit que vous étiez fiancée à Georges.<br>Ça c'est ce qu'il voulait faire croire. Et il y est arrivé.<br>Vous êtes en train de me dire qu'il a menti ? Vous le traitez de menteur !<br>Oh oui, un menteur hors pair, mais avec bien d'autres défauts que celui-là. Vous savez, il était amoureux de moi. Mais vous pouvez pas savoir ce qu'il était lourd et collant. Bien sûr, aujourd'hui, j'ai des regrets. Avec le recul, je me dis que j'aurais peut-être dû agir autrement, mais c'était impossible. Parce qu'il y avait aucune femme qui aurait voulu de lui à cette époque là. Il était trop balourd, trop patot, il voulait pas me lâcher la touffe.",

    "Bonjour M'dame. Madame, j'voulais vous dire : je vous aime.<br>Ah ben ça, on va le savoir, vous arrêtez pas de me le répéter. Vous savez bien que je ne vous aime pas Georges.<br>Oui, j'sais bien.<br>Alors, qu'est-ce que vous voulez ?<br>J'aime vos seins, vos loches.<br>Les bras m'en tombent.",

    "Vous m'trouvez pas désirable ?<br>C'est pas ça Georges. C'est pas que vous êtes pas désirables, mais avec les femmes, vous manquez de tact, en gros.<br>Dites-donc vos verres, ils sont crados.<br>Et alors, j'suis pas votre bonne !<br>Ben n'empêche qu'une fois qu'j'vous aurais... blbllblbl<br>Georges ! Je vous ai déjà dit de ne pas parler en buvant, c'est mauvais pour l'estomac.<br>Brbllbb, 'scusez moi M'dame.",

    "Moi j'pense qu'il avait pas plus de classe que d'beurre au cul. J'ai jamais compris comment il a eu le titre. Pourtant, j'aimerai pas que l'homme qui l'a tué vous échappe.<br>Eh, oh, ça va hein? Y a pas le feu, on est pas aux pièces.",

    "Mon cher Peter, je touche enfin au but. Que d'émotions devant cette simple bicoque tant désirée, que d'émotion, mais que de fierté aussi ! Hervé Claude, Jean-Claude Narcy, faites place, ténors du journalisme ! J'arrive !<br>Entre, fouille-merde, je vais t'en donner moi du biscuit sur Georges pour ta feuille de chou. Ça va fuser les potins, les ragots. C'est ma profession moi de témoigner, mes témoignages c'est pas de la daube.<br>Mais j'suis un peu surpris, quand vous m'avez appelé, vous m'avez dit que vous aviez bien connu Georges et que vous aviez de vraies informations.<br>Mais faut pas de vrai information pour vendre un journal. La vérité ça n'a jamais intéressé personne. Tiens, regarde Georges par exemple ! La vérité, c'est que pendant qu'il était pénard à faire du cheval, moi j'étais super loin sur mon bateau à la pêche. Mais faut savoir la rendre excitante la vérité. Moi à la pêche, lui sur son cheval. Moi à la pêche, lui le cheval. Oh oui, c'est bon comme ça.",

    "Bon, on arrête les déguisements, c'est que des emmerdes. Le journalisme total, c'est totalement con.<br>Allez !<br>Patron ! Patron, il faut qu'on vous parle, vite !<br>Vous voulez me parlez des chiottes, peut-être ?<br>Non, on veut vous parlez de l'affaire Abitbol.<br>On veut laisser tomber nos déguisements. On en a marre.<br>Comme vous le sentez.",

    "Ahh ahh hum hummm .. Mais c'est le sympathique Dave que voilà, il a remis son ancienne chemise ?<br>Est-ce que vous voulez être ma femme? Et après, on boira un café.<br>Ça peut marcher... En y réfléchissant bien, j'pense que notre histoire n'a pas une chance sur cent de marcher. On divorce ?<br>Hum humm hummm.<br>J'imagine que j'aurai pas de pension, radin !",
    
    "Monsieur ? Vous savez parler avec l'accent canadien ?<br>Ben évidemment, y a qu'à demander. Mais dites-moi, Georges Abitbol, vous pouvez m'en parler ?<br>Monsieur Dave...<br>Comment vous connaissez mon nom ?<br>J'ai vu le début du flim... Vous savez parler comme ça en plissant du visage ? Ça a l'air facile, en fait c'est pas évident.<br>Parlez-moi de Georges Abitbol, au lieu de jouer !<br>Hey, vous pensez qu'à travailler ? J'parie qu'vous êtes même pas capable de parler comme ça.<br>Mouais, ça c'est vrai.<br>Ben faut apprendre, faut pas rester comme ça !<br>On vit très bien sans savoir.",

    "Salut, ça va ?<br>Écoutes, j'ai un truc à te proposer, vachement bien, super balaise. On serait tout les deux complètement irresponsables, payés par la CIA, avec un hélicoptère.<br>Un hélicoptère ?<br>Un super hélicoptère, qu'on a intelligemment appelé 'supercopter'<br>Vendu !<br>Ahhh !<br>Oh les cons !",

    "Regarde c'est lui ! Il est là !<br>Qui ? le jus de tomate ?<br>Non, l'acteur !<br>Humm hummm...<br>Dites-moi, vous pourriez nous parler de Georges Abitbol?<br>Humm hummm...<br>Essayez de trouver un moyen de raconter votre histoire, même sans ouvrir la bouche.<br>Ou, ou, ou vous pouvez la mimer.<br>Vous êtes un grand acteur, vous devriez pouvoir le faire, n'est ce pas ?<br>Ok, j'vais vous la mimer... J'étais à la cueillette au champignon...",

    "Mais bordel, ça doit pas être la saison, c'est pas possible.<br>Hep ! Monsieur !<br>Ouais ? quoi ?<br>...<br>Vas-y parle, qu'est-ce que tu veux ?<br>Je vais vous poser une question, si vous répondez bien, je vous laisse le passage.<br>Vas-y dépêche toi, pose moi ta question !<br>Top ! Qui suis-je ? Je suis un animateur de France 3, je suis déguisé en noir. Mon émission passe tous les soirs à 18h35, je pose des questions à des champions... Je suis ? Je suis ?<br>Tu es... Tu es Julien Lepers ? C'est ça ?<br>Oui! C'est ça, je suis Julien Lepers !<br>Bien.. sacré Julien va !<br>Hey ! Votre encyclopédie Larousse !",

    "C'est après cet épisode que j'ai croisé très furtivement Georges Abitbol.<br>Mon chéri ! Nous étions séparés, mais quelle importance, nous sommes réunis !<br>Tu vois cet homme là ? Il est très connu, par contre, avant ça, c'était un parfait inconnu. C'est fou non ? Qu'est-ce que tu en penses ?<br>Je pense qu'il est très grand.<br>Par contre avant, il était petit.",
    
    "Hop hop hop ! Et notre répétition de scie musicale ?<br>Excusez-moi maestro, je saluais des amis philosophes",

    "Merci de ce témoignage. Dites-moi, j'ai un trou de mémoire, vous pouvez me dire le titre de votre plus grand film ?<br>Ou, ou, ou nous le mimez.<br>Oui, essayez de nous mimer le titre de votre plus grand film, s'il vous plaît.<br>Humm hummm",

    "Putain, il est costaud cet acteur.<br>Dis-donc, j'pense à un truc, tu l'as acheté où ta veste ?<br>En même temps que mon fûte, chez un mec dans les Vosges, tu connais pas.<br>Ah ouaih, ouaih... C'est vrai que t'es vosgiens toi !",

    "Que j'vous parle de Georges ?<br>S'il vous plaît, oui.<br>Ce que j'peux raconter, c'est que moi j'l'ai jamais rencontré Georges. Je sais que c'était l'homme le plus classe du monde, mais c'est tout. Moi ? J'suis un type qui a fait beaucoup pour l'écologie. J'vous assure, c'est vrai. Tiens, si j'vous disais qu'y a rien que j'adorais plus que les longues chevauchées solitaires, dans les grands espaces vierges. La communion intime avec la nature, l'extase des sens, un sentiment grisant de liberté : l'osmose quoi !<br>Dites-moi, à propos de Georges, quelqu'un aurait eu intérêt à vouloir sa mort ? Vous lui connaissiez un ennemi, ou même un rival ?<br>Oui, j'ai entendu parler d'un type, un dénommé Joël, il avait un ami manchot.",

    "Abitbol !<br>J'ai peut-être qu'un bras, mais j'suis pas manchot !<br>Mais naturellement.<br>En puissance intellectuelle, on va voir s'que tu vaux.<br>Mais avec plaisir !<br>Très bien, c'est une devinette. Qu'est ce qui a trois bras, un seul chapeau, deux chemises et une veste... un foulard, un pistolet et quatre oreilles ?<br>Mais c'est toi et ton...<br>Mais aucun problème, c'est le cowboy de Tchernobyl.<br>Bravo, il la connaissait !<br>Au revoir messieurs dames... C'est ça, la puissance intellectuelle... Bac+2 les enfants.<br>Oh ça sent la pluie ça. On va rentrer, et on va s'inventer une petite charade, et là, il s'ra bien feinté!",
    
    "Ecoute moi bien garçon. L'affaire Abitbol, c'est pas une affaire pour vous. Et mon patron n'aime pas trop les fouineurs. Alors j'vais te dire une chose : y a de la boue qui vaut mieux pas la remuer.",

    "Uhuh uhuh uhuh uh<br> Qu'est-ce tu dis ?<br>Nan, je demandais si on avait pas reçu mes tricots de peau en polystyrène expansé. Je comprends pas, ils auraient dû être là.<br>Demande au standard.<br>Ah merci, on se sent vraiment aidé.<br>Oui le standard? Vous avez rien reçu pour moi ?<br>Vous commencez à faire chier, professeur, vous savez ça ? Bon, quittez pas, j'ai un appel pour vous.<br>Allo, oui ? Bonjour. Professeur Hamon.<br>Professeur, j'enquête sur Georges Abitbol, et je voudrais vous poser deux ou trois questions sur votre père, Joël Hamon. Je pourrais avoir votre témoignage ?<br>C'est bien... Actuellement, j'ai un léger problème de costume. Je crois que mon tailleur se fout de ma gueule, mais ça devrait pas tarder à s'arranger, je n'suis pas inquiet. Euh... voyons-nous chez moi, cet après-midi. Hum ? vers cinq heures.<br>Ben.... attendez, il faut que je me souvienne de tout... Chez vous, vers 5 heures? Bon je vais essayer de m'en rappeler, hein?<br>J'espère.",

    "Purée ! Ah ah ! Ça j'aime ! Ah ah ah. Vous arrivez, vous êtes même pas chez vous. Vous vous pointez avec trois quart d'heure de retard. Pas bonjour, pas merci ! Vous filez tout droit au frigo, vous prenez la dernière bière ! Ah ah... Vous, vous êtes un sacré sans-gêne.<br>Merci... Bon, arrêtez, vous me gênez et je vais rougir. En réalité, j'aimerais que... que vous me parliez de votre papa, de Joël Hamon. C'est possible ?<br>Bien-sûr, c'est possible.<br>Hum hum.<br>Je vais vous raconter une histoire pas banale. Une fois, je devais rejoindre mon père Joël dans une carrière où il travaillait avec des ouvriers.",

    "Vive la révolution d'octobre! Il parait qu'on a repéré des animaux préhistoriques partouzeurs de droite dans les parages.<br>Comment peux-tu croire à des conneries pareilles.<br>Juste avant d'arriver au chantier, je m'étais arrêté quelques instants pour faire boire mon cheval.<br>Huuuuuuu<br>Oww oww oww...<br>Regarde ! Joël n'y va pas ! Reste ici, Joël !<br>Je reviens! Je dois y aller !",

    "Ouaaaais!!!<br>Ouf... Eh ben! on l'a bien eu!<br>Je déteste les animaux préhistoriques partouzeurs de droite, bordel. C'est de la merde ! Mélanger comme ça partouze et politique. C'est mieux de faire les choses dans l'ordre !<br>Va te faire branler, trotskard !",

    "Voilà. Et mon père, vous allez me demander où il était, pendant que nous, on se battait. Nan ?<br>Dites-moi... Votre père, où il était pendant que vous vous battiez ?<br>Ahhh ah ah ah ah ah ! Joël ?  Mais il a fait comme à chaque fois qu'il y avait du grabuge ! Joël ? Ah ah ah ah ah ah ah... Aujourd'hui il est mort. Dieu ait son âme. Bah je peux pas dire de mal, mais pendant que nous on risquait notre vie contre les animaux préhistoriques partouzeurs de droite, lui, comme à son habitude, il allait s'isoler dans la montagne. Personne n'a jamais su ce qu'il faisait, d'ailleurs.",

    "S'il vous plaît. Je peux vous parler, Madame ?<br>Appelez-moi Christelle. Mon mari est absent. Vous voulez voir mes fesses ? Et ensuite je vous roulerai une pelle.<br>Merci, madame, Ce serait avec plaisir, mais d'abord, je dois vous questionner.<br>Comme vous voudrez. Mais après, faudra être mignon avec moi. C'est bien. Je sais pourquoi vous êtes là. Vous cherchez quelqu'un qui aurait pu en vouloir à Georges, c'est ça ? Georges... Je faisais l'amour avec lui depuis le samedi après-midi, jusqu'au vendredi soir. Ah... à ce moment-là, c'était un bon compagnon.",

    "Tu voulais me voir chérie ?<br>Oui, je voulais te voir. Je voulais absolument que tu sois là, je tenais à te présenter mon ex.<br>Oh... t'es lourde...<br>J'ai très bien entendu.<br>Bon, excuse-moi.<br>T'avises pas de recommencer. Yves, je te présente Georges, l'homme le plus classe du monde. Georges, je te présente Yves, mon ex.<br>C'est lui, Georges ? Et bien bravo. Permets-moi de te demander ce que tu fais avec un mec pareil.<br>Bababababababa... j'ai les bonbons qui collent au papier.<br>Mon cher Yves, je vais te dire pourquoi je suis avec Georges. J'aime les hommes qui ont de la classe.<br>J'ai envie d'aller aux gogues.<br>Encore que parfois, il arrive que les apparences soient trompeuses.<br>Bohhh Christelle, ton mec, je vais lui massacrer la tête. Mais pas tout de suite. Non, pas maintenant. Quand il s'y attendra pas.<br>C'est pas très très courageux.",
    
    "J'en ai rien à foutre d'être courageux. Tout ce que je sais, c'est qu'il va payer. Que ce soit demain ou même dans vingt ans, il va mourir. Et il mourra pas de sa belle mort, crois-moi.<br>Tu préfères pas qu'on fasse la paix, plutôt?<br>C'est tout ce que t'as à dire? Fais quelque chose.<br>Qu'est-ce que tu veux que je fasse?<br>Je sais pas, moi. Va te battre. C'est notre honneur qui est en jeu.<br>Si c'est notre honneur, vas-y toi, te battre.",

    "Georges finit par se lasser de moi. Alors il est parti avec une québécoise. Une belle petite salope.<br>À propos de salope, euh.. tout à l'heure, avant que vous commenciez votre histoire, vous m'aviez proposé de... comment dire... de faire le le... euh... j'aimerais bien passer à l'acte sexuel.<br>Oh.... je ne sais pas...<br>Écoutez.<brOui oui.<br>J'ai plus beaucoup de temps.<brMoi non plus.<br>Alors il faut que vous preniez une décision. Moi je suis à bloc. Dîtes-moi si c'est oui ou si c'est non.<br>C'est non.",

    "Allo Steven?<br><br>Bouge pas, Dave. Peter te prend sur l'autre ligne.<br>C'est bon.<br>Bien. Faisons un point. Je vais voir Yves dans son restaurant, ça se passe plutôt mal.<br>Quoi ? T'es pas mort ?<br>J'me suis fait avoiner. Je me suis fait casser la gueule par un mec, une brute, il voulait que je parle, mais j'ai rien dit du tout. J'ai pas dit où en était l'enquête, malgré la douleur.<br>Encore heureux que t'as pas dit où en était l'enquête, parce que vu qu'on est au point zéro, si tu l'avais dit, on passait pour des busards.<br>Pourquoi il t'envoie son gorille, alors que d'après son témoignage, il est innocent ?<br>C'est ça, c'est à n'y rien comprendre, même en y réfléchissant bien ! Un mec que rien ne permet de soupçonner m'aiguille sur Joël, le rival de Georges, puis me fait dérouiller par son homme de main. Pourquoi ?<br>Oui, pourquoi, pourquoi, pourquoi ?",
    
    "Les enfants. Écoutez. Je crois que j'ai le fin mot de l'histoire. Suivez bien. Georges Abitbol s'est fait assassiné par Yves. Le mobile: une femme, Christelle. Sexe + histoire de cul = meurtre.<br>Bien joué Peter! L'enquête touche à sa fin! On va devenir célèbres, on va bientôt niquer ! On va bientôt niquer !<br>*smack* Mettez des capotes.",

    "Gorge profonde ! Gorge profonde ? Gorge profonde ? Vous avez demandé à me voir ? Vous avez des révélations ?<br>Voui... Des révélations d'une importance extrême. Abitbol est pas crevé. Il est même vivant, ouais!<br>Vous êtes ivre, gorge profonde. Vous empestez, vous ne savez plus ce que vous dites. Abitbol est mort !<br>Pas du tout du tout. Georges est vivant, et il est revenu en ville. C'est moi qui te le dis, p'tit merdeux, va ! Georges il est bien vivant ! Merde... Et il est revenu pour se venger! voilà! Et et et l'assassin de Georges, et ben c'est Yves !<br>Ça, on le savait.<br>Monsieur je sais tout et bien puisque t'es si malin, tu vas te démerder tout seul! Et moi, ma gorge profonde, m'en vais la remplir derechef !<br>Qu'est-ce que c'est ? Des voitures dans les parkings, maintenant ?",

    "Arrrgl.<br>Je ne te connais pas, j'ai rien contre toi, mais faut que je tape sur quelqu'un. C'est pas de bol pour toi, sinon je garde tout en dedans et c'est pas bon. Alors tiens ! Le prends pas mal, mais... Tiens !<br>Un autre type : Mais qu'est-ce que c'est que ce raffut?<br>Alors ? on peut plus chier tranquille ?",

    "Abitbol ! Soit disant l'homme le plus classe du monde !<br>Du calme Gaël !<br>Quoi, du calme ?<br>Du calme...<br>Mais pourquoi tu dis ça ?<br>Babloche !<br>Mais oui, j'suis un bab, bé alors ? Ça te défrise, vieux réac' ? Parce que j'ai les cheveux long, tu flippes pour ton confort bourgeois ? T'as un mauvais karma, frère, si tu supportes pas mes cheveux. Désolé papy, mais j'ai ma liberté d'expression capillaire. Ça te fait chier, hein dis-le, Georges...<br>Putain !... Putain, t'es nul !",

    "Messieurs, Georges Abitbol<br>Georges... mais tu es vivant?<br>Miracle... un miracle ! Il marche !<br>Bon, on va pas en faire un fromage ? Je m'en suis sorti sans problème. C'est pas vrai cette affaire ? Qu'est-ce que c'est ? Qu'est-ce que c'est ce pataquès ? Je suis là pour une raison précise, je veux l'adresse de l'homme qui a voulu me tuer.<br>Yves ?<br>Ouais.<br>OK. J'imagine l'état dans lequel vous devez être. Mais comportez vous en bon américain, Georges. Faites honneur à votre drapeau. Vous devez laisser la justice faire son boulot. Hum...<br>Ah croyez-nous, on aimerait bien vous aider, seulement on l'a perdue, cette adresse. Alors même, on voudrait vous la donner, qu'on pourrait pas.<br>Mais vous me prenez pour une buse ? Je suis l'homme le plus classe du monde, bande de cons.<br>Du calme, Abitbol.<br>Vous méritez même pas que je m'énerve. Je vais me débrouiller sans vous. Merci pour votre aide.<br>Ah, mais il a vraiment pris la grosse tête.",

    "Alors Georges ? Qu'est-ce que tu veux comme tuyau ?<br>Trouve-moi l'adresse du type, là, qu'a voulu m'assassiner. Ça me fera plaisir.<br>Mais tu sais, je commence à en avoir plein le cul. Ouais, plein le cul. Nan mais c'est vrai. C'est pas une raison parce que je donne à tout le monde des bons tuyaux que je mérite pas un peu d'amour ?<br>T'as raison Huggy, je t'aime.<br>Ah ouais ? C'est pas croyable. Il faut que je m'énerve, que je te fasse mon numéro pour que tu me le dises ?<br>Ah ah ah ah ah ah ah! Tu nous fais ta crise ? Ta petite parano ? ah ah ah...<br>Eh pour le feu, merci pigeon!<br>Eh ! Et toi, ton tuyau t'as qu'à te le mettre dans le cul!<br>Huggy, j'ai vraiment besoin de toi. S'il te plait. Donne-moi l'adresse d'Yves.<br>D'accord. Mais seulement pour du fric. Ça te coûtera trente francs.<br>Ouais...<br>Payables en deux fois! Quinze francs avant, et quinze francs après.",

    "Allez !<br>Patron! Patron ! Il faut qu'on vous parle ! Vite !<br>Vous savez que Georges sort de mon bureau ?<br>Rien à foutre de ça, y'a plus important.<br>Georges Abitbol est vivant. Bien vivant.<br>Bien joué, les gars.",

    "Yves ? C'est moi, Georges. T'inquiète pas, je ne te ferai rien. Je suis venu pour te faire la paix, pas dans un esprit de vengeance. Je sais que c'est toi qui a essayé de m'assassiner. Je sais aussi que tu t'es jamais remis de l'histoire de Christelle. Mais c'est du passé. Tournons-nous plutôt vers l'avenir. Ce que je veux, c'est que tu t'excuses gentiment.<br>Ouais, je m'excuse.<br>Excuse-toi mieux que ça.<br>Ben euh... pardon, j'te prie de m'excuser.<br>Pardon mon doux seigneur.<br>Pardon mon doux seigneur.<br>Éteins ta clope.",

    "Cocoricoooo !<br>Monsieur Peter !<br>Quoi ?<br>Tenez, vous avez un message de Dave.<br>Vous avez une clope ?.. Merci<br>Il est parti chercher Georges dans l'hôtel de Yves.<br>Hum hum...<br>Merci pour la clope, grosse vache.<br>Bonne journée.<br>Merci.<br>Dites-moi, vous pouvez me donner l'heure, s'il vous plaît ?<br>Oui, 9h01.<br>Ah vous êtes précis, vous.<br>Oui. Vous voulez niquer avec mon ami et moi ?<br>Ben oui, pourquoi pas ?<br>Répétez ce que vous venez de me dire ? Vous avez bien dit 'oui, pourquoi pas ?', c'est bien ça ?<br>Oui, exactement.<br>Suivez-moi. C'est quoi votre prénom ?<br>C'est Sophie, mais tout le monde m'appelle Sosso. Mais ? Mais qu'est-ce que j'ai dit ?<br>Il faut que je vous présente Steven.",

    "Euh euh.. Steven ! Laisse tomber ce connard. Victoire, vieux, victoire ! Viens voir par ici, viens! Madame Sosso, je vous présente Steven. Steven, Madame Sosso.<br>Mademoiselle !<br>Asseyez-vous... Tiens, prends une chaise... Dites-lui ce que vous venez de me dire.<br>Et bien j'lui ai dit que je voulais bien niquer avec vous.<br>T'entends ça ? Qu'est-ce que t'en dis ?<br>Outch.<br>Et en plus, on n'est pas célèbre. On n'a pas publié encore une seule ligne. Et alors, pourquoi ?<br>Ah, parce que je m'en fous, de ça. J'ai pas de problème. Vous avez l'air tous de tomber des nues.<br>Vous pouvez pas savoir ce que ça représente pour nous. Je flashe !<br>Si je comprends bien, on s'est tapé une enquête super dure, alors que si on vous avait rencontré avant, on aurait pu niquer tout de suite, sans même être célèbres ?<br>Alors que moi, pendant ce temps-là, je me la suis donné grave.<br>Allez !",

    "Patron ! Patron, il faut qu'on vous parle, vite! On veut savoir si on peut prendre notre après-midi.<br>C'est-à-dire qu'on a un plan, là.<br>Attendez les gars... On sait pas encore ce que veut dire 'monde de merde'.<br>'Monde de merde'... 'Monde de merde'... Ah oui ! Mais Dave est parti chercher Georges ?<br>Comme ça, dès qu'ils reviennent, on demande à Georges d'expliquer 'monde de merde'.<br>Ok les gars...",

    "Ça va bien, m'sieur Abitbol ? Vous avez passé une bonne nuit, sans être indiscret ?<br>Au poil. Et t'es pas indiscret. Je suis majeur, et je fais ce que j'ai envie de faire avec mon petit corps.<br>Dites-moi, là, pendant que je vous tiens là. Ca veut dire quoi 'monde de merde', sans être indiscret ?<br>Tu te réveilles à 35 ans pour te demander ce que ça veut dire 'monde de merde' ? C'est pas que t'es indiscret, c'est juste que t'es un con. En disant 'monde de merde' j'ai voulu dire que le monde allait mal. C'est un cri de révolte que j'ai lancé à mes frères opprimés. Finissons-en avec la résignation et l'indifférence. Ouvrons les yeux! Partout l'injustice, le nationalisme, l'exclusion. Ça me débecte...",
    
    "T'as déjà entendu parlé de l'hégémonie du grand capital ?<br>Non.<br>Tu t'intéresses pas à la politique ? Bah... Tu devrais. Faut se mettre au travail, afin de vaincre les fanascismes. C'est un concept à moi, ça dénonce à la fois les fascistes et les fanatiques.<br>Merci, m'sieur Abitbol. Vous m'avez ouvert les yeux.<br>Hein... Regarde plutôt la route.",

    "Aaaaaaah... Monde de merde !<br>Ouais, moi aussi, j'ai bien envie de le dire... Monde de merde !",
];
